### PR TITLE
Fix perform to main thread after picking image from camera

### PR DESCRIPTION
**Pull request by yulichandra**
cause : still in background ?
fix : perform delegate in MainThread

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by ZZBHuang** [comment]
Did you try to put 
>     dispatch_async(dispatch_get_main_queue(), ^{  //Do something  });
inside the delegate
>  - (void)photoPickerViewController:(YMSPhotoPickerViewController *)picker didFinishPickingImage:(UIImage *)image
?

**Comment by yulichandra** [comment]
ok thanks. Since i didn't do image processing after taking photo so i don't come up with that solution.

**Pull request closed without merging**
